---
title: "Tradeoffs in fitness"
author: "Ada Yan"
date: "`r Sys.Date()`"
output: bookdown::html_document2
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE, echo=FALSE)
```

```{r include = FALSE}
rm(list = ls())
devtools::load_all("../")
library(tidyverse)
library(odin)
library(deSolve)
library(showtext)
showtext_auto()
```

```{r}
R_0_max_plotting <- 15
AUC_max_plotting <- 3e5
max_plotting_tibble <- tibble(name = c("R_0", "AUC"),
                              x = c(0, 0),
                              y = c(R_0_max_plotting, AUC_max_plotting)) %>%
  mutate(name = factor(name, levels = c("R_0", "AUC")))


model_filename <- "innate_adaptive_two_compartment.R"
# compile ODEs
gen <- compile_model(model_filename)

simple_solve <- function(gen, pars, solving_time) {
  mod <- gen$new(user = pars)
  sol <- solve_ODE_error_handling(mod, solving_time, tol = -Inf) %>%
    as_tibble()
  sol
}
```

```{r pars, echo = TRUE}
# Cao et al. 2015
# combined with Handel et al. 2007 for the simpler antibody model
pars <- get_default_pars()
pars <- c(pars, list(gamma1 = 1e-4, gamma2 = 1e-3))


solving_time <- seq(0, 20, by = .01)

pars_two_compartment <- as.list(pars)
pars_two_compartment$p <- rep(pars[["p"]], 2)
pars_two_compartment$q <- rep(pars[["q"]], 2)
pars_two_compartment$rho <- rep(pars[["rho"]], 2)
pars_two_compartment$phi <- rep(pars[["phi"]], 2)
pars_two_compartment$alpha <- .5
```

```{r}
calc_R_0 <- function(pars) {
  sum(pars$beta1 * pars$p * c(pars$alpha, 1 - pars$alpha) * pars$T_0) / pars$delta / (pars$c1 + pars$k1 * pars$A_0)
}

solve_wrapper <- function(gen) {
  solve_model <- function(pars, solving_time) {
    simple_solve(gen = gen, pars = pars, solving_time = solving_time) %>%
      select(t, V, starts_with("AUC"), starts_with("dose_response")) %>%
      mutate(R_0 = calc_R_0(pars))
  }
  solve_model
}

solve_model <- solve_wrapper(gen)
```

# Vary $T_{0i}$ and $\beta_i$

```{r}
beta1_minus_beta2_on_sum_beta_vec <- seq(-1, 1, length.out = 21)

alpha_vec <- 0.8

calc_betas <- function(mean_beta1, beta1_minus_beta2_on_sum_beta) {
  mean_beta1 * c(1 + beta1_minus_beta2_on_sum_beta, 1 - beta1_minus_beta2_on_sum_beta)
}

beta1_alpha_grid <- expand_grid(beta1_minus_beta2_on_sum_beta = beta1_minus_beta2_on_sum_beta_vec, alpha = alpha_vec)

change_beta1_alpha_wrapper <- function(pars, beta1_minus_beta2_on_sum_beta, alpha) {
  pars$beta1 <- calc_betas(pars$beta1, beta1_minus_beta2_on_sum_beta)
  pars$alpha <- alpha
  solve_model(pars, solving_time) %>%
    mutate(beta1_minus_beta2_on_sum_beta = beta1_minus_beta2_on_sum_beta,
           alpha = alpha)
}

sols_vary_T_0 <- apply_named_args(beta1_alpha_grid, 1, 
                                  \(beta1_minus_beta2_on_sum_beta, alpha) change_beta1_alpha_wrapper(pars_two_compartment, beta1_minus_beta2_on_sum_beta, alpha)) %>%
  bind_rows()
```

```{r}
plot_AUC <- function(sols, AUC_name = "AUC") {
  
  g <- sols %>%
    filter(t == max(solving_time)) %>%
    ggplot(aes(x = beta1_minus_beta2_on_sum_beta, y = .data[[AUC_name]])) +
    geom_line() +
    theme_bw(base_size = 16, base_family= "Arial") +
    xlab(latex2exp::TeX("$(\\beta_1- \\beta_2)/(\\beta_1 + \\beta_2)$")) +
    ylab(AUC_name)
  if(AUC_name == "AUC") {
    g <- g + coord_cartesian(xlim = c(-1, 1), ylim = c(0, 3e5))
  } else {
    g <- g + coord_cartesian(xlim = c(-1, 1)) + expand_limits(y = 0)
  }
  g
}

plot_V <- function(sols) {
  sols %>%
    ggplot(aes(x = t, y = V, color = beta1_minus_beta2_on_sum_beta, group = beta1_minus_beta2_on_sum_beta)) +
    geom_line() +
    scale_y_log10(latex2exp::TeX("Viral load (TCID$_{50}$)"), limits = c(1, 1e6), breaks = 10^seq(0, 8, by = 2)) +
    coord_cartesian(xlim = c(0, 10)) +
    theme_bw(base_size = 16, base_family= "Arial") +
    xlab("Time (days)") +
    labs(color = latex2exp::TeX("$(\\beta_1- \\beta_2)/(\\beta_1 + \\beta_2)$"))
}

plot_R_0 <- function(sols) {
  sols %>%
    ggplot(aes(x = beta1_minus_beta2_on_sum_beta, y = R_0)) +
    geom_line() +
    coord_cartesian(xlim = c(-1, 1), ylim = c(0, 25)) +
    theme_bw(base_size = 16, base_family = "Arial") +
    xlab(latex2exp::TeX("$(\\beta_1- \\beta_2)/(\\beta_1 + \\beta_2)$")) +
    ylab(latex2exp::TeX("$R_0$")) +
    labs(color = latex2exp::TeX("$T_{0,1}/T_0$"))
}
```




# With TIV model

```{r}
pars_TIV <- pars_two_compartment
pars_TIV$k1 <- 0
pars_TIV$q <- c(0, 0)
sols_TIV <- apply_named_args(beta1_alpha_grid, 1, 
                             \(beta1_minus_beta2_on_sum_beta, alpha) change_beta1_alpha_wrapper(pars_TIV, beta1_minus_beta2_on_sum_beta, alpha)) %>%
  bind_rows()
```

```{r fig.width = 6, fig.height = 3}
plot_tropisms <- seq(-1, 1, by = .5)
# (g <- plot_V(sols_TIV) +
(g <- plot_V(filter(sols_TIV, beta1_minus_beta2_on_sum_beta %in% plot_tropisms)) +
   scale_y_log10(latex2exp::TeX("Viral load (TCID$_{50}$)"), limits = c(1, 1e8), breaks = 10^seq(0, 8, by = 2)) +
   coord_cartesian(xlim = c(0, 20)))
ggsave("Fig6.pdf", g, height = 3, width = 6)
```

```{r fig.width = 8, fig.height = 3}
# all on one plot

# g <- bind_rows(mutate(sols_vary_T_0, model = "Immune"),
#                mutate(sols_TIV, model = "TIV")) %>%
#   filter(t == max(t)) %>%
#   select(model, beta1_minus_beta2_on_sum_beta, AUC, AUC_log10, dose_response1) %>%
#   rename(Model = model) %>%
#   pivot_longer(cols = AUC:dose_response1, names_to = "Transmissibility metric", values_to = "Value") %>%
#   mutate(`Transmissibility metric` = case_match(`Transmissibility metric`,
#                                                 "AUC" ~ "AUC",
#                                                 "AUC_log10" ~ "AUC log scale",
#                                                 "dose_response1" ~"Dose response")) %>%
#   # group_by(Model, `Transmissibility function`) %>%
#   # mutate(value = value / max(value)) %>%
#   ggplot(aes(x = beta1_minus_beta2_on_sum_beta, y = Value)) +
#   ggh4x::facet_grid2(Model~`Transmissibility metric`, scales = "free", independent = "all") +
#   # facet_grid(Model~ `Transmissibility metric`, scales = "free") +
#   theme(strip.placement = "outside") + # Optional: adjust label placement
#   geom_line() + 
#   theme_bw(base_size = 16) +
#   xlab(latex2exp::TeX("$(\\beta_1- \\beta_2)/(\\beta_1 + \\beta_2)$")) +
#   scale_x_continuous(sec.axis = sec_axis(~ . , name = "Transmissibility metric", breaks = NULL, labels = NULL)) +
#   scale_y_continuous(sec.axis = sec_axis(~ . , name = "Model", breaks = NULL, labels = NULL)) +
#   expand_limits(y = c(0))

g <- bind_rows(mutate(sols_vary_T_0, model = "Immune"),
               mutate(sols_TIV, model = "TIV")) %>%
  filter(t == max(t)) %>%
  select(model, beta1_minus_beta2_on_sum_beta, AUC, AUC_log10, dose_response1) %>%
  rename(Model = model) %>%
  pivot_longer(cols = AUC:dose_response1, names_to = "Transmissibility metric", values_to = "Value") %>%
  mutate(`Transmissibility metric` = case_match(`Transmissibility metric`,
                                                "AUC" ~ "AUC",
                                                "AUC_log10" ~ "AUC log scale",
                                                "dose_response1" ~"Dose response")) %>%
  # group_by(Model, `Transmissibility function`) %>%
  # mutate(value = value / max(value)) %>%
  ggplot(aes(x = beta1_minus_beta2_on_sum_beta, y = Value)) +
  facet_wrap(~`Transmissibility metric`, scales = "free") +
  # ggh4x::facet_grid2(Model~`Transmissibility metric`, scales = "free", independent = "all") +
  # facet_grid(Model~ `Transmissibility metric`, scales = "free") +
  # theme(strip.placement = "outside") + # Optional: adjust label placement
  geom_line(aes(color = Model, group = Model)) + 
  theme_bw(base_size = 16) +
  xlab(latex2exp::TeX("$(\\beta_1- \\beta_2)/(\\beta_1 + \\beta_2)$")) +
  scale_x_continuous(sec.axis = sec_axis(~ . , name = "Transmissibility metric", breaks = NULL, labels = NULL)) +
  # scale_y_continuous(sec.axis = sec_axis(~ . , name = "Model", breaks = NULL, labels = NULL)) +
  expand_limits(y = c(0))
ggsave("Fig5_draft.pdf", g, width = 8, height = 3)
g
```

# Vary $p_i$ and $\beta_i$

```{r}
p1_vec <- pars$p*1.6

beta1_p1_grid <- expand_grid(beta1_minus_beta2_on_sum_beta = beta1_minus_beta2_on_sum_beta_vec, p1 = p1_vec)

change_beta1_p1_wrapper <- function(pars, beta1_minus_beta2_on_sum_beta, p1) {
  pars$beta1 <- calc_betas(pars$beta1, beta1_minus_beta2_on_sum_beta)
  pars$p <- c(p1, 2 * mean(pars$p) - p1)
  solve_model(pars, solving_time) %>%
    mutate(beta1_minus_beta2_on_sum_beta = beta1_minus_beta2_on_sum_beta,
           p1 = p1)
}

sols_vary_p <- apply_named_args(beta1_p1_grid, 1, 
                                \(beta1_minus_beta2_on_sum_beta, p1) change_beta1_p1_wrapper(pars_two_compartment, beta1_minus_beta2_on_sum_beta, p1)) %>%
  bind_rows()
```



# Vary $T_{0i}$, $p_i$ and $\beta_i$

```{r}
beta1_p1_alpha_grid <- expand_grid(beta1_minus_beta2_on_sum_beta = beta1_minus_beta2_on_sum_beta_vec, 
                                   p1 = c(0.42, 0.49, 0.63),
                                   alpha = 0.3)

change_beta1_p1_alpha_wrapper <- function(pars, beta1_minus_beta2_on_sum_beta, p1, alpha) {
  pars$beta1 <- calc_betas(pars$beta1, beta1_minus_beta2_on_sum_beta)
  pars$alpha <- alpha
  pars$p <- c(p1, 2 * mean(pars$p) - p1)
  solve_model(pars, solving_time) %>%
    mutate(beta1_minus_beta2_on_sum_beta = beta1_minus_beta2_on_sum_beta,
           alpha = alpha,
           p1 = p1,
           p1T1_on_T0 = p1 * alpha,
           p2T2_on_T0 = pars$p[2] * (1 - alpha))
}

sols <- apply_named_args(beta1_p1_alpha_grid, 1, 
                         \(beta1_minus_beta2_on_sum_beta, p1, alpha) change_beta1_p1_alpha_wrapper(pars_two_compartment, beta1_minus_beta2_on_sum_beta, p1, alpha)) %>%
  bind_rows() %>%
  mutate(alpha = round(alpha, 2),
         p1 = round(p1, 2),
         case_name = case_when(p1 == 0.42 ~ "p1 T1 < p2 T2",
                               p1 == 0.49 ~ "p1 T1 = p2 T2",
                               p1 == 0.63 ~ "p1 T1 > p2 T2"))
```


```{r fig.width = 5, fig.height = 3}

(g <- sols %>%
  filter(t == max(solving_time)) %>%
  ggplot(aes(x = beta1_minus_beta2_on_sum_beta, y = R_0, color = case_name, group = case_name)) +
  geom_line() +
  coord_cartesian(xlim = c(-1, 1), ylim = c(0, R_0_max_plotting)) +
  theme_bw(base_size = 16) +
  xlab(latex2exp::TeX("$(\\beta_1- \\beta_2)/(\\beta_1 + \\beta_2)$")) +
  ylab(latex2exp::TeX("$R_0$")) +
  labs(color = "") +
  scale_color_discrete(labels = unname(latex2exp::TeX(c("$p_1 T_{01} < p_2 T_{02}$", "$p_1 T_{01} = p_2 T_{02}$", "$p_1 T_{01} > p_2 T_{02}$")))))
ggsave("Fig4a.pdf", g, height = 3, width = 5)

```

```{r fig.width = 5, fig.height = 3}
(g <- sols %>%
  filter(t == max(solving_time)) %>%
  ggplot(aes(x = beta1_minus_beta2_on_sum_beta, y = AUC, color = case_name, group = case_name)) +
  geom_line() +
  coord_cartesian(xlim = c(-1, 1), ylim = c(0, AUC_max_plotting)) +
  theme_bw(base_size = 16) +
  xlab(latex2exp::TeX("$(\\beta_1- \\beta_2)/(\\beta_1 + \\beta_2)$")) +
  ylab("AUC") +
  labs(color = "") +
  scale_color_discrete(labels = unname(latex2exp::TeX(c("$p_1 T_{01} < p_2 T_{02}$", "$p_1 T_{01} = p_2 T_{02}$", "$p_1 T_{01} > p_2 T_{02}$")))))
ggsave("Fig4c.pdf", g, height = 3, width = 5)

```


# Change $q_i$ and $\beta_i

```{r}
# beta1_vec <- beta1_vec[seq(2, 8)]
beta1_q1_grid <- expand_grid(beta1_minus_beta2_on_sum_beta = beta1_minus_beta2_on_sum_beta_vec, 
                             q1 = pars_two_compartment$q[[1]] * 1.5)

change_beta1_q1_wrapper <- function(pars, beta1_minus_beta2_on_sum_beta, q1) {
  pars$beta1 <- calc_betas(pars$beta1, beta1_minus_beta2_on_sum_beta)
  pars$q <- rev(c(q1, 2 * mean(pars$q) - q1))
  solve_model(pars, solving_time) %>%
    mutate(beta1_minus_beta2_on_sum_beta = beta1_minus_beta2_on_sum_beta,
           q1 = q1)
}

sols_vary_q <- apply_named_args(beta1_q1_grid, 1, 
                                \(beta1_minus_beta2_on_sum_beta, q1) change_beta1_q1_wrapper(pars_two_compartment, beta1_minus_beta2_on_sum_beta, q1)) %>%
  bind_rows()
```



# Change $p_i$, $q_i$ and $\beta_i$

```{r}
p1_vec <- 1.1*pars$p
q1_vec <- c(0.000125, 0.000150, 0.000175)
beta1_p1_q1_grid <- expand_grid(beta1_minus_beta2_on_sum_beta = beta1_minus_beta2_on_sum_beta_vec, 
                                p1 = p1_vec,
                                q1 = q1_vec)

change_beta1_p1_q1_wrapper <- function(pars, beta1_minus_beta2_on_sum_beta, p1, q1) {
  pars$beta1 <- calc_betas(pars$beta1, beta1_minus_beta2_on_sum_beta)
  pars$p <- c(p1, 2 * mean(pars$p) - p1)
  pars$q <- c(q1, 2 * mean(pars$q) - q1)
  solve_model(pars, solving_time) %>%
    mutate(beta1_minus_beta2_on_sum_beta = beta1_minus_beta2_on_sum_beta,
           p1 = p1,
           q1 = q1)
}

sols <- apply_named_args(beta1_p1_q1_grid, 1, 
                         \(beta1_minus_beta2_on_sum_beta, p1, q1) change_beta1_p1_q1_wrapper(pars_two_compartment, beta1_minus_beta2_on_sum_beta, p1, q1)) %>%
  bind_rows() %>%
  mutate(p1_on_p = signif(p1 / mean(pars_two_compartment$p), 3),
         q1_minus_q2_on_q = signif((q1 - 2 * mean(pars_two_compartment$q) + q1) / mean(pars_two_compartment$q), 3))
```


```{r}
plot_AUC <- function(sols) {
  sols %>%
    filter(t == max(solving_time)) %>%
    mutate(q1_minus_q2_on_q = factor(q1_minus_q2_on_q)) %>%
    ggplot(aes(x = beta1_minus_beta2_on_sum_beta, y = AUC, color = q1_minus_q2_on_q, group = q1_minus_q2_on_q)) +
    geom_line() +
    theme_bw(base_size = 16) +
    xlab(latex2exp::TeX("$(\\beta_1- \\beta_2)/(\\beta_1 + \\beta_2)$")) +
    ylab("AUC") +
    expand_limits(y = 0) +
    labs(color = latex2exp::TeX("$(q_1 - q_2)/\\bar{q}$"))
}

# plot_V <- function(sols, p1_on_p, q1_on_q) {
#   sols %>%
#     filter(p1_on_p == !!p1_on_p,
#            q1_on_q == !!q1_on_q,
#            beta1_on_beta %in% seq(0, 2, by = .5)) %>%
#     ggplot(aes(x = t, y = V, color = beta1_minusbeta_2_on_beta, group = beta1_minusbeta_2_on_beta)) +
#     geom_line() +
#     scale_y_log10("Viral load", limits = c(1, 1e6), breaks = 10^seq(0, 8, by = 2)) +
#     coord_cartesian(xlim = c(0, 7)) +
#     theme_bw(base_size = 16) +
#     xlab("Time (days)") +
#     labs(color = latex2exp::TeX("$(\\beta_1- \\beta_2)/(\\beta_1 + \\beta_2)$")) +
#     ggtitle(latex2exp::TeX(paste0("(q_1 - q_2)/\\bar{q} = ", (q1_on_q -1)*2, "$")))
# }
```

```{r fig.width = 5, fig.height = 3}

(g <- sols %>%
  mutate(q1_minus_q2_on_q = factor(q1_minus_q2_on_q)) %>%
  filter(t == max(solving_time)) %>%
  ggplot(aes(x = beta1_minus_beta2_on_sum_beta, y = R_0, color = q1_minus_q2_on_q, group = q1_minus_q2_on_q)) +
  geom_line() +
  coord_cartesian(xlim = c(-1, 1), ylim = c(0, R_0_max_plotting)) +
  theme_bw(base_size = 16) +
  xlab(latex2exp::TeX("$(\\beta_1- \\beta_2)/(\\beta_1 + \\beta_2)$")) +
  ylab(latex2exp::TeX("$R_0$")) +
  labs(color = latex2exp::TeX("$(q_1 - q_2)/\\bar{q}$"))) #+
# scale_color_discrete(labels = unname(latex2exp::TeX(c("$q_1 < q_2$", "$q_1 = q_2$", "$q_1 > q_2$"))))
ggsave("Fig4b.pdf", g, height = 3, width = 5)
```

```{r fig.width = 5, fig.height = 3}
(g <- plot_AUC(sols) +
  coord_cartesian(ylim = c(0, AUC_max_plotting)))
ggsave("Fig4d.pdf", g, height = 3, width = 5)
```


All on one page:
```{r fig.width = 10, fig.height = 3}
all_sols <- bind_rows(mutate(sols_vary_T_0, scenario = "A: unequal cell abundances"),
                      mutate(sols_vary_p, scenario = "B: unequal virus production rates"),
                      mutate(sols_vary_q, scenario = "C: unequal interferon production rates"))

(g <- all_sols %>%
    filter(beta1_minus_beta2_on_sum_beta %in% plot_tropisms) %>%
    ggplot(aes(x = t, y = V, color = beta1_minus_beta2_on_sum_beta, group = beta1_minus_beta2_on_sum_beta)) +
    facet_wrap(~scenario, labeller = label_wrap_gen(width = 25)) +
    geom_line() +
    scale_y_log10(latex2exp::TeX("Viral load (TCID$_{50}$)"), limits = c(1, 1e6), breaks = 10^seq(0, 8, by = 2)) +
    coord_cartesian(xlim = c(0, 10)) +
    theme_bw(base_size = 16) +
    xlab("Time (days)") +
    labs(color = latex2exp::TeX("$(\\beta_1- \\beta_2)/(\\beta_1 + \\beta_2)$")))
ggsave("Fig2.pdf", g, width = 10, height = 3)

(g <- g + scale_y_continuous(latex2exp::TeX("Viral load (TCID$_{50}$)")))
ggsave("Fig2_supp.pdf", g, width = 10, height = 3)
```
```{r fig.width = 8, fig.height = 6}

(g <- all_sols %>%
    filter(t == max(t)) %>%
    select(scenario, beta1_minus_beta2_on_sum_beta, R_0, AUC) %>%
    pivot_longer(cols = c(R_0, AUC)) %>%
    mutate(name = factor(name, levels = c("R_0", "AUC"))) %>%
    ggplot(aes(x = beta1_minus_beta2_on_sum_beta, y = value)) +
    facet_grid(name~scenario, scales = "free", labeller = label_wrap_gen(width = 25), switch = "y") +
    geom_line() +
    geom_blank(data = max_plotting_tibble, aes(x = x, y = y)) +
    theme_bw(base_size = 16) +
    xlab(latex2exp::TeX("$(\\beta_1- \\beta_2)/(\\beta_1 + \\beta_2)$")) +
    expand_limits(y = 0) +
    theme(strip.placement = "outside") +
    ylab(""))
ggsave("Fig3.pdf", g, width = 8, height = 6)
```

```{r}
```
